version: '3.5'
volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.100.87,nolock,soft,rw"
      device: ":/mnt/data/bitwarden"
services:
   software:
     image: mprasil/bitwarden
     networks:
       - internal
     deploy: 
       labels:
         traefik.enable: "true"
         traefik.backend: "biwarden"
         traefik.docker.network: "internal"
         traefik.frontend.rule: "Host:biwarden.leejonchapman.com"
         traefik.web.port: "80"
         traefik.frontend.headers.SSLRedirect: "true"
         traefik.frontend.headers.SSLHost: "biwarden.leejonchapman.com"
       mode: global
       placement:
         constraints:
           - node.role == worker
     environment: 
       - "SIGNUPS_ALLOWED=false"
     volumes:
       - data:/data
networks:
  internal:
    name: internal
    external: true
