version: '3.5'
volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.100.87,nolock,soft,rw"
      device: ":/mnt/data/bitwarden"
services:
   software:
     image: mprasil/bitwarden
     restart: unless-stopped
     networks:
       - internal_routeable
     labels:
       - "traefik.enable=true"
       - "traefik.frontend.rule=Host:bitwarden1.leejonchapman.com"
       - "traefik.frontend.passHostHeader=true"
       - "traefik.frontend.headers.SSLRedirect=true"
     volumes:
       - data:/data
     deploy:
       replicas: 1
networks:
  internal_routeable:
    name: internal_routeable
    external: true
