version: '3.5'
volumes:
  data:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.100.87,nolock,soft,rw"
      device: ":/mnt/data/bitwarden"
services:
   software:
     image: bitwardenrs/server:latest
     networks:
       - internal
     deploy: 
       labels:
         traefik.enable: "true"
         traefik.backend: "bitwarden"
         traefik.docker.network: "internal"
         traefik.frontend.rule: "Host:bitwarden.leejonchapman.com"
         traefik.web.port: "80"
         traefik.frontend.headers.SSLRedirect: "true"
         traefik.frontend.headers.SSLHost: "bitwarden.leejonchapman.com"
         traefik.backend.loadbalancer.stickiness: "true"
       # sqllite DB doesnt scale and corrupts - do not scale - it will corrupt
       replicas: 1
       placement:
         constraints:
           - node.role == worker
       restart_policy:
         condition: any
         max_attempts: 3
     environment: 
       - "SIGNUPS_ALLOWED=false"
     volumes:
       - data:/data
networks:
  internal:
    name: internal
    external: true
